Matplotlib created a temporary config/cache directory at /tmp/matplotlib-6k2iulr4 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-l58rc48v because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-5azlgjdu because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-wwxm90mt because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-9pn8a0tf because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-m7onrh_i because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-u9wapc9l because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-x55r2bu3 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-sjan26ix because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-2bu7uyn0 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-3a8pemmd because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-1uymywt8 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-96f7hx12 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-uo2i5ihl because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-5bewtu6_ because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-pfxu6fzf because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-7htegry2 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-c_ueuzhv because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-2b7eoinc because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-f0xf6hde because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-t1g4quqb because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-q94vjgrv because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-wy33o1vo because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-rufmsbgt because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-2s5dwrct because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-5g5bjm4f because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-0qljpnin because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-63gk8987 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-obpzcnaw because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-7ap2vksx because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-1evhs9op because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-_bfboxrg because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-plkymd1c because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-yizhx_2m because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-53dycb7y because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-0439r18z because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-3j_w3otv because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-zzs6uu0i because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-oyy69vuc because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-smjofju4 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-feu62gh1 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-90v99a8c because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-z75mpuof because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-urjklp3b because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-_rehcjl9 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-6nz17xfk because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-i03ybeng because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
Matplotlib created a temporary config/cache directory at /tmp/matplotlib-mzi91bs1 because the default path (/ccs/home/mrowan/.config/matplotlib) is not a writable directory; it is highly recommended to set the MPLCONFIGDIR environment variable to a writable directory, in particular to speed up the import of Matplotlib and to better support multiprocessing.
:::MLLOG {"namespace": "", "time_ms": 1617329341816, "event_type": "POINT_IN_TIME", "key": "submission_benchmark", "value": "deepcam", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 56}}
:::MLLOG {"namespace": "", "time_ms": 1617329341983, "event_type": "POINT_IN_TIME", "key": "submission_org", "value": "Umbrella Corp.", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 59}}
:::MLLOG {"namespace": "", "time_ms": 1617329341984, "event_type": "POINT_IN_TIME", "key": "submission_division", "value": "closed", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 62}}
:::MLLOG {"namespace": "", "time_ms": 1617329341984, "event_type": "POINT_IN_TIME", "key": "submission_status", "value": "onprem", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 65}}
:::MLLOG {"namespace": "", "time_ms": 1617329341984, "event_type": "POINT_IN_TIME", "key": "submission_platform", "value": "48xSUBMISSION_PLATFORM_PLACEHOLDER", "metadata": {"file": "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/utils/mlperf_log_utils.py", "lineno": 68}}
:::MLLOG {"namespace": "", "time_ms": 1617329341984, "event_type": "INTERVAL_START", "key": "init_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 109}}
:::MLLOG {"namespace": "", "time_ms": 1617329341984, "event_type": "POINT_IN_TIME", "key": "cache_clear", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 110}}
:::MLLOG {"namespace": "", "time_ms": 1617329341985, "event_type": "POINT_IN_TIME", "key": "seed", "value": 333, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 114}}
:::MLLOG {"namespace": "", "time_ms": 1617329341989, "event_type": "POINT_IN_TIME", "key": "global_batch_size", "value": 192, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 187}}
:::MLLOG {"namespace": "", "time_ms": 1617329341989, "event_type": "POINT_IN_TIME", "key": "opt_name", "value": "LAMB", "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 188}}
:::MLLOG {"namespace": "", "time_ms": 1617329341989, "event_type": "POINT_IN_TIME", "key": "opt_base_learning_rate", "value": 0.001, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 189}}
:::MLLOG {"namespace": "", "time_ms": 1617329341989, "event_type": "POINT_IN_TIME", "key": "opt_learning_rate_warmup_steps", "value": 0, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 190}}
:::MLLOG {"namespace": "", "time_ms": 1617329341989, "event_type": "POINT_IN_TIME", "key": "opt_learning_rate_warmup_factor", "value": 1.0, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 191}}
:::MLLOG {"namespace": "", "time_ms": 1617329341989, "event_type": "POINT_IN_TIME", "key": "opt_epsilon", "value": 1e-08, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 192}}
Constructing DeepLabv3+ model...
Number of output channels: 3
Output stride: 16
Number of Input Channels: 16
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Initialized dataset with  5760  samples.
Initialized dataset with  576  samples.
:::MLLOG {"namespace": "", "time_ms": 1617329345838, "event_type": "POINT_IN_TIME", "key": "train_samples", "value": 5760, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 309}}
:::MLLOG {"namespace": "", "time_ms": 1617329345838, "event_type": "POINT_IN_TIME", "key": "eval_samples", "value": 576, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 314}}
:::MLLOG {"namespace": "", "time_ms": 1617329357473, "event_type": "INTERVAL_END", "key": "init_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 335}}
:::MLLOG {"namespace": "", "time_ms": 1617329357474, "event_type": "INTERVAL_START", "key": "run_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 336}}
:::MLLOG {"namespace": "", "time_ms": 1617329357476, "event_type": "INTERVAL_START", "key": "epoch_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 342, "epoch_num": 1, "step_num": 0}}
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.88 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.88 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 150.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 190.94 MiB free; 14.17 GiB reserved in total by PyTorch)
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 580, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 352, in main
    outputs = net.forward(inputs)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/parallel/distributed.py", line 560, in forward
    result = self.module(*inputs, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 463, in forward
    x = self.upsample(x, low_level_features, input.size())
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/gpfs/alpine/aph114/scratch/mrowan/ml-performance-benchmark/deepcam/summit/src/deepCam/architecture/deeplab_xception.py", line 382, in forward
    x = self.last_deconv(x)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/module.py", line 722, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/sw/summit/open-ce/anaconda-base/envs/open-ce-0.1-0/lib/python3.6/site-packages/torch/nn/modules/conv.py", line 907, in forward
    output_padding, self.groups, self.dilation)
  File "/ccs/home/mrowan/.local/lib/python3.6/site-packages/apex/amp/wrap.py", line 28, in wrapper
    return orig_fn(*new_args, **kwargs)
RuntimeError: CUDA out of memory. Tried to allocate 432.00 MiB (GPU 0; 15.75 GiB total capacity; 12.95 GiB already allocated; 174.94 MiB free; 14.17 GiB reserved in total by PyTorch)
CUDA Hook Library: Failed to find symbol mem_find_dreg_entries, python: undefined symbol: __PAMI_Invalidate_region
