:::MLLOG {"namespace": "", "time_ms": 1624299309147, "event_type": "POINT_IN_TIME", "key": "submission_benchmark", "value": "deepcam", "metadata": {"file": "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/utils/mlperf_log_utils.py", "lineno": 56}}
:::MLLOG {"namespace": "", "time_ms": 1624299309361, "event_type": "POINT_IN_TIME", "key": "submission_org", "value": "Umbrella Corp.", "metadata": {"file": "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/utils/mlperf_log_utils.py", "lineno": 59}}
:::MLLOG {"namespace": "", "time_ms": 1624299309361, "event_type": "POINT_IN_TIME", "key": "submission_division", "value": "closed", "metadata": {"file": "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/utils/mlperf_log_utils.py", "lineno": 62}}
:::MLLOG {"namespace": "", "time_ms": 1624299309362, "event_type": "POINT_IN_TIME", "key": "submission_status", "value": "onprem", "metadata": {"file": "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/utils/mlperf_log_utils.py", "lineno": 65}}
:::MLLOG {"namespace": "", "time_ms": 1624299309362, "event_type": "POINT_IN_TIME", "key": "submission_platform", "value": "8xSUBMISSION_PLATFORM_PLACEHOLDER", "metadata": {"file": "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/utils/mlperf_log_utils.py", "lineno": 68}}
:::MLLOG {"namespace": "", "time_ms": 1624299309362, "event_type": "INTERVAL_START", "key": "init_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 109}}
:::MLLOG {"namespace": "", "time_ms": 1624299309362, "event_type": "POINT_IN_TIME", "key": "cache_clear", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 110}}
:::MLLOG {"namespace": "", "time_ms": 1624299309362, "event_type": "POINT_IN_TIME", "key": "seed", "value": 333, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 114}}
:::MLLOG {"namespace": "", "time_ms": 1624299309367, "event_type": "POINT_IN_TIME", "key": "global_batch_size", "value": 16, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 187}}
:::MLLOG {"namespace": "", "time_ms": 1624299309367, "event_type": "POINT_IN_TIME", "key": "opt_name", "value": "LAMB", "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 188}}
:::MLLOG {"namespace": "", "time_ms": 1624299309367, "event_type": "POINT_IN_TIME", "key": "opt_base_learning_rate", "value": 0.001, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 189}}
:::MLLOG {"namespace": "", "time_ms": 1624299309367, "event_type": "POINT_IN_TIME", "key": "opt_learning_rate_warmup_steps", "value": 0, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 190}}
:::MLLOG {"namespace": "", "time_ms": 1624299309368, "event_type": "POINT_IN_TIME", "key": "opt_learning_rate_warmup_factor", "value": 1.0, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 191}}
:::MLLOG {"namespace": "", "time_ms": 1624299309368, "event_type": "POINT_IN_TIME", "key": "opt_epsilon", "value": 1e-08, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 192}}
Constructing DeepLabv3+ model...
Number of output channels: 3
Output stride: 16
Number of Input Channels: 16
Selected optimization level O1:  Insert automatic casts around Pytorch functions and Tensor methods.

Defaults for this optimization level are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Processing user overrides (additional kwargs that are not None)...
After processing overrides, optimization options are:
enabled                : True
opt_level              : O1
cast_model_type        : None
patch_torch_functions  : True
keep_batchnorm_fp32    : None
master_weights         : None
loss_scale             : dynamic
Initialized dataset with  121264  samples.
Initialized dataset with  15158  samples.
:::MLLOG {"namespace": "", "time_ms": 1624299311634, "event_type": "POINT_IN_TIME", "key": "train_samples", "value": 121264, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 309}}
:::MLLOG {"namespace": "", "time_ms": 1624299311634, "event_type": "POINT_IN_TIME", "key": "eval_samples", "value": 15158, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 314}}
:::MLLOG {"namespace": "", "time_ms": 1624299316219, "event_type": "INTERVAL_END", "key": "init_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 335}}
:::MLLOG {"namespace": "", "time_ms": 1624299316220, "event_type": "INTERVAL_START", "key": "run_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 336}}
:::MLLOG {"namespace": "", "time_ms": 1624299316220, "event_type": "INTERVAL_START", "key": "epoch_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 342, "epoch_num": 1, "step_num": 0}}
:::MLLOG {"namespace": "", "time_ms": 1624299397064, "event_type": "POINT_IN_TIME", "key": "learning_rate", "value": 0.001, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 412, "epoch_num": 1, "step_num": 100}}
:::MLLOG {"namespace": "", "time_ms": 1624299397065, "event_type": "POINT_IN_TIME", "key": "train_accuracy", "value": 0.42516443133354187, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 413, "epoch_num": 1, "step_num": 100}}
:::MLLOG {"namespace": "", "time_ms": 1624299397065, "event_type": "POINT_IN_TIME", "key": "train_loss", "value": 0.04394523799419403, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 414, "epoch_num": 1, "step_num": 100}}
:::MLLOG {"namespace": "", "time_ms": 1624299397065, "event_type": "INTERVAL_START", "key": "eval_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 425, "epoch_num": 1}}
/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/utils/visualizer.py:110: UserWarning: No contour levels were found within the data range.
  tc_contour = self.my_map.contour(self.x_map, self.y_map, p1, [0.5], linewidths=3, colors='orange', alpha=0.9, ax=ax)
:::MLLOG {"namespace": "", "time_ms": 1624299888667, "event_type": "POINT_IN_TIME", "key": "eval_accuracy", "value": 0.43916881504403615, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 497, "epoch_num": 1, "step_num": 100}}
:::MLLOG {"namespace": "", "time_ms": 1624299888668, "event_type": "POINT_IN_TIME", "key": "eval_loss", "value": 0.050994297243514154, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 498, "epoch_num": 1, "step_num": 100}}
:::MLLOG {"namespace": "", "time_ms": 1624299888669, "event_type": "INTERVAL_END", "key": "eval_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 512, "epoch_num": 1}}
:::MLLOG {"namespace": "", "time_ms": 1624299888670, "event_type": "INTERVAL_START", "key": "save_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 516, "epoch_num": 1, "step_num": 100}}
:::MLLOG {"namespace": "", "time_ms": 1624299889374, "event_type": "INTERVAL_END", "key": "save_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 527, "epoch_num": 1, "step_num": 100}}
:::MLLOG {"namespace": "", "time_ms": 1624299959044, "event_type": "POINT_IN_TIME", "key": "learning_rate", "value": 0.001, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 412, "epoch_num": 1, "step_num": 200}}
:::MLLOG {"namespace": "", "time_ms": 1624299959045, "event_type": "POINT_IN_TIME", "key": "train_accuracy", "value": 0.5387046337127686, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 413, "epoch_num": 1, "step_num": 200}}
:::MLLOG {"namespace": "", "time_ms": 1624299959045, "event_type": "POINT_IN_TIME", "key": "train_loss", "value": 0.03344136103987694, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 414, "epoch_num": 1, "step_num": 200}}
:::MLLOG {"namespace": "", "time_ms": 1624299959045, "event_type": "INTERVAL_START", "key": "eval_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 425, "epoch_num": 1}}
:::MLLOG {"namespace": "", "time_ms": 1624300453263, "event_type": "POINT_IN_TIME", "key": "eval_accuracy", "value": 0.5091602503113043, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 497, "epoch_num": 1, "step_num": 200}}
:::MLLOG {"namespace": "", "time_ms": 1624300453274, "event_type": "POINT_IN_TIME", "key": "eval_loss", "value": 0.04561774342807841, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 498, "epoch_num": 1, "step_num": 200}}
:::MLLOG {"namespace": "", "time_ms": 1624300453276, "event_type": "INTERVAL_END", "key": "eval_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 512, "epoch_num": 1}}
:::MLLOG {"namespace": "", "time_ms": 1624300453276, "event_type": "INTERVAL_START", "key": "save_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 516, "epoch_num": 1, "step_num": 200}}
:::MLLOG {"namespace": "", "time_ms": 1624300453982, "event_type": "INTERVAL_END", "key": "save_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 527, "epoch_num": 1, "step_num": 200}}
:::MLLOG {"namespace": "", "time_ms": 1624300528260, "event_type": "POINT_IN_TIME", "key": "learning_rate", "value": 0.001, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 412, "epoch_num": 1, "step_num": 300}}
:::MLLOG {"namespace": "", "time_ms": 1624300528261, "event_type": "POINT_IN_TIME", "key": "train_accuracy", "value": 0.5719452500343323, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 413, "epoch_num": 1, "step_num": 300}}
:::MLLOG {"namespace": "", "time_ms": 1624300528261, "event_type": "POINT_IN_TIME", "key": "train_loss", "value": 0.031071234494447708, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 414, "epoch_num": 1, "step_num": 300}}
:::MLLOG {"namespace": "", "time_ms": 1624300528261, "event_type": "INTERVAL_START", "key": "eval_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 425, "epoch_num": 1}}
/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/utils/visualizer.py:113: UserWarning: No contour levels were found within the data range.
  tc_contour = self.my_map.contour(self.x_map, self.y_map, l1, [0.5], linewidths=3, colors='orange', alpha=0.9, ax=ax)
:::MLLOG {"namespace": "", "time_ms": 1624301016907, "event_type": "POINT_IN_TIME", "key": "eval_accuracy", "value": 0.5686418810405397, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 497, "epoch_num": 1, "step_num": 300}}
:::MLLOG {"namespace": "", "time_ms": 1624301016925, "event_type": "POINT_IN_TIME", "key": "eval_loss", "value": 0.03177435955848397, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 498, "epoch_num": 1, "step_num": 300}}
:::MLLOG {"namespace": "", "time_ms": 1624301016926, "event_type": "INTERVAL_END", "key": "eval_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 512, "epoch_num": 1}}
:::MLLOG {"namespace": "", "time_ms": 1624301016926, "event_type": "INTERVAL_START", "key": "save_start", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 516, "epoch_num": 1, "step_num": 300}}
:::MLLOG {"namespace": "", "time_ms": 1624301017684, "event_type": "INTERVAL_END", "key": "save_stop", "value": null, "metadata": {"file": "src/deepCam/train_hdf5_ddp.py", "lineno": 527, "epoch_num": 1, "step_num": 300}}
Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-2011-07-19-05-4.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-1999-03-06-03-1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-1998-12-17-04-5.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-2001-07-29-05-5.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-2007-10-06-06-2.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-2010-08-25-05-3.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-2005-01-22-03-4.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

Traceback (most recent call last):
  File "src/deepCam/train_hdf5_ddp.py", line 581, in <module>
    main(pargs)
  File "src/deepCam/train_hdf5_ddp.py", line 345, in main
    for inputs, label, filename in train_loader:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 819, in __next__
    return self._process_data(data)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 846, in _process_data
    data.reraise()
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/_utils.py", line 385, in reraise
    raise self.exc_type(msg)
OSError: Caught OSError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
    data = fetcher.fetch(index)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 44, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/global/cscratch1/sd/mrowan/ml-performance-benchmark/deepcam/cori/src/deepCam/data/cam_hdf5_dataset.py", line 121, in __getitem__
    with h5.File(filename, "r") as f:
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 408, in __init__
    swmr=swmr)
  File "/global/homes/m/mrowan/.conda/envs/mlperf_deepcam/lib/python3.7/site-packages/h5py/_hl/files.py", line 173, in make_fid
    fid = h5f.open(name, flags, fapl=fapl)
  File "h5py/_objects.pyx", line 54, in h5py._objects.with_phil.wrapper
  File "h5py/_objects.pyx", line 55, in h5py._objects.with_phil.wrapper
  File "h5py/h5f.pyx", line 88, in h5py.h5f.open
OSError: Unable to open file (unable to open file: name = '/global/cscratch1/sd/tkurth/data/cam5_data/All-Hist/train/data-2000-05-05-06-1.h5', errno = 2, error message = 'No such file or directory', flags = 0, o_flags = 0)

